chore: add meme generator workshop
hack-club-brasil/website pull request #13
Opened 2021-03-29 04:49 UTC by adrianoapj

🇺🇸  This PR adds a new workshop: The Meme Generator!
🇧🇷  Esta PR adiciona um novo workshop: O Gerador de Memes!

2021-04-01 10:47 UTC, farreltobias requested changes
Algumas alterações e sugestões submetidas! :)

2021-04-01 10:47 UTC, farreltobias commented on docs/workshops/gerador-de-memes/README.md
> +Para começarmos, vá para [https://repl.it/languages/html](https://repl.it/languages/html). Seu ambiente de desenvolvimento vai aparecer em poucos segundos!
![image](https://user-images.githubusercontent.com/54959451/112974466-e31d4e00-9128-11eb-8332-b08697f68755.png)

Repl.it mudou, agr é necessário criar uma conta para iniciar um projeto. Mesmo que não consta na tradução original, seria melhor atualizar o conteúdo e pedir ao leitor criar sua conta ou logar no repl.it?

2021-04-01 10:47 UTC, farreltobias commented on docs/workshops/gerador-de-memes/README.md
> +    ![Meme mostrando texto de cima e texto de baixo](img/meme_com_texto.png)
No documento os campos de texto foram chamados de "Texto de Cima" e "Texto de baixo", enquanto na imagem é nomeado como "Valor de cima" e "Valor de baixo". 

Original:
![image](https://user-images.githubusercontent.com/54959451/112975599-3ba11b00-912a-11eb-85a5-f9a4a2426727.png)

Tradução em pt-br:
![image](https://user-images.githubusercontent.com/54959451/112975905-99cdfe00-912a-11eb-8b72-4f196355f7eb.png)

Para facilitar o trabalho recomendo gerar outra imagem com os valores nomeados como escrito no documento.

2021-04-01 10:47 UTC, farreltobias commented on docs/workshops/gerador-de-memes/README.md
> +* Agora desejamos que nossos memes tenham 2 campos de texto: ***Texto de Cima*** e ***Texto de Baixo***, parecido com isso:
Mudar "(...) 2 campos de texto (...)" para "dois campos de texto", por questões de legibilidade.

2021-04-01 10:47 UTC, farreltobias commented on docs/workshops/gerador-de-memes/README.md
> +* Certo, mas nós também precisamos de algo para mostrar o meme, correto?
Sugestão: remover o "certo". O certo como afirmação no início + o correto no final como pergunta ficou um pouco confuso. (Opinião minha, não é necessário retirar).

2021-04-01 10:47 UTC, farreltobias commented on docs/workshops/gerador-de-memes/README.md
> +Se você não criou uma conta no [repl.it](https://repl.it), o faça para que você consiga salvar essa sua maravilhosa criação!
Repl.it mudou, agr é necessário criar uma conta para iniciar um projeto. Mesmo que não consta na tradução original, seria melhor atualizar o conteúdo e apenas pedir para o usuário criar uma conta

2021-04-01 10:47 UTC, farreltobias commented on docs/workshops/gerador-de-memes/README.md
> +Se você está tendo problemas para se cadastrar, fale com um líder de seu clube ou com alguém no [Slack do Hack Club](https://hackclub.com/slack)!
Colocar este texto na Parte 2 do documento, onde será pedido ao usuário criar uma conta no repl.it

2021-04-01 20:49 UTC, adrianoapj commented on docs/workshops/gerador-de-memes/README.md
> +    ![Meme mostrando texto de cima e texto de baixo](img/meme_com_texto.png)
Acredito que seja mais fácil mudar o texto ao invés de mudar a imagem, já que não vai ter nenhuma mudança significativa no entendimento ao mudar de "texto" para "valor"

2021-04-01 20:50 UTC, adrianoapj commented on docs/workshops/gerador-de-memes/README.md
> +    ![Meme mostrando texto de cima e texto de baixo](img/meme_com_texto.png)
Na real, faz mais sentido deixar "texto" mesmo, já que está sendo utilizado assim no restante do workshop 🤔

2021-04-05 09:44 UTC, farreltobias requested changes

2021-04-05 09:44 UTC, farreltobias commented on docs/workshops/gerador-de-memes/README.md
>  Se você está tendo problemas para se cadastrar, fale com um líder de seu clube ou com alguém no [Slack do Hack Club](https://hackclub.com/slack)!
Colocar este texto na Parte 2 do documento, onde será pedido ao usuário criar uma conta no repl.it

2021-04-05 09:47 UTC, farreltobias requested changes

2021-04-05 09:47 UTC, farreltobias commented on docs/workshops/gerador-de-memes/README.md
>  Se você está tendo problemas para se cadastrar, fale com um líder de seu clube ou com alguém no [Slack do Hack Club](https://hackclub.com/slack)!
É melhor tmb colocar o link da comunidade no discord, assim a pessoa pode falar diretamente com a gente

2021-04-05 09:48 UTC, farreltobias commented on docs/workshops/gerador-de-memes/README.md
>  Se você está tendo problemas para se cadastrar, fale com um líder de seu clube ou com alguém no [Slack do Hack Club](https://hackclub.com/slack)!
É melhor também colocar a comunidade do discord para que a pessoa possa falar diretamente com a gente

2021-04-05 10:06 UTC, farreltobias approved these changes

2021-04-05 10:07 UTC, merged