added kanye workshop
hack-club-brasil/website pull request #2
Opened 2021-01-28 17:52 UTC by vitorvavolizza

vejam se está tudo certinho para nós podermos dar merge :)

2021-02-11 23:44 UTC, gabriellimma commented
- [pass] kanye workshop
- [pass] spinning wheel workshop

2021-03-29 04:53 UTC, adrianoapj commented
🇺🇸 Wow! 40 files changed :O
I will take some time to review that, but I will do it asap

🇧🇷 Uau! 40 arquivos modificados :O
Eu vou demorar um pouco para revisar isso, mas o farei assim que possível

2021-04-01 10:57 UTC, farreltobias commented
@gabriellimma, quais workshops já passaram por review? Ou quer fazer review de todos os 7 workshops criados nessa pr?

2021-04-01 12:42 UTC, vitorvavolizza commented
isso @farreltobias, faltam apenas o jogo da velha, sintetizador e o mundos-vr.

2021-04-01 13:01 UTC, farreltobias commented
Beleza, eu faço o review do **sintetizador**, assim tem mais dois workshops para o @adrianoapj e o @gabriellimma fazerem review, caso queiram que eu faça review de +1 ou até de todos haha, me deem um toque,

2021-04-01 15:51 UTC, gabriellimma commented
@farreltobias pode deixar comigo o jogo da velha

2021-04-01 16:03 UTC, gabriellimma commented
[pass] jogo-da-velha

2021-04-06 04:42 UTC, adrianoapj requested changes
Antes de qualquer coisa, parabéns pelo excelente trabalho, @vitorvavolizza e @gabriellimma.
Contudo, ao fazer a revisão, identifiquei alguns pequenos problemas que acredito que necessitam de atenção :)

2021-04-06 04:42 UTC, adrianoapj commented on docs/workshops/aventura-de-texto-rust/README.md
> +- Também movemos todas as respostas corretas para sua própria função. para manter nosso código mais claro
```suggestion
- Também movemos todas as respostas corretas para sua própria função, para manter nosso código mais claro
```

2021-04-06 04:42 UTC, adrianoapj commented on docs/workshops/calculadora-react/README.md
> +Para começar, vá para este [código inicial](https://codesandbox.io/s/calculadora-inicial-nu23b). Pressione **`ctrl+s`** / **`cmd+s`** e ele irá automaticamente copiá-lo para você. Agora, temos tudo p
```suggestion
Para começar, vá para este [código inicial](https://codesandbox.io/s/calculadora-inicial-nu23b). Pressione **`ctrl+s`** (Windows/Linux) ou **`cmd+s`** (macOS) e ele irá automaticamente copiá-lo para você. Agora, temos tudo pronto, então vamos começar!
```

2021-04-06 04:42 UTC, adrianoapj commented on docs/workshops/calculadora-react/README.md
> +Primeiro, há 2 diretórios principais e um arquivo `package.json`. Vamos ignorar o arquivo `package.json` por enquanto e vamos dar uma olhada nos 2 diretórios, `public/` e `src/`.
```suggestion
Primeiro, há 2 diretórios principais e um arquivo `package.json`. Vamos ignorar o arquivo `package.json` por enquanto e vamos dar uma olhada nos 2 diretórios: `public/` e `src/`.
```

2021-04-06 04:42 UTC, adrianoapj commented on docs/workshops/calculadora-react/README.md
> +Explicação: Aqui, `useState` já é importado para você, pois o utilizaremos na parte final do workshop A seguir, há um conjunto contendo todos os operadores básicos. O componente `App` simplesmente re
```suggestion
Explicação: Aqui, `useState` já é importado para você, pois o utilizaremos na parte final do workshop. A seguir, há um conjunto contendo todos os operadores básicos. O componente `App` simplesmente renderiza um cabeçalho e um `div` com um `nome de classe` de `calc-wrapper` por enquanto.
```

2021-04-06 04:42 UTC, adrianoapj commented on docs/workshops/calculadora-react/README.md
> +Explicação: Criamos uma função chamada `ehNum` que aceita um `val` como argumento. Em seguida, ela verifica se o `val` é um número, `C` (limpar) ou um decimal (`.`), se alguma das condições for verda
```suggestion
Explicação: Criamos uma função chamada `ehNum` que aceita um `val` como argumento. Em seguida, ela verifica se o `val` é um número, `C` (limpar) ou um decimal (`.`), se alguma das condições for verdadeira, ela retorna `verdadeiro`, ou então, simplesmente retorna `falso`.
```

2021-04-06 04:42 UTC, adrianoapj commented on docs/workshops/calculadora-react/README.md
> +2. `onClick` - Essa prop irá simplesmente armazenar as funções que criaremos mais tarde para nossa calculadora. Esta função será passada para o componente `onClick` do Botão.
```suggestion
2. `onClick` - Essa prop irá simplesmente armazenar as funções que criaremos mais tarde para nossa calculadora. Esta função será passada para o valor `onClick` do botão.
```

2021-04-06 04:42 UTC, adrianoapj commented on docs/workshops/calculadora-react/README.md
> +Explicação: Primeiro aceitamos as 3 props neste componente. Depois, utilizamos `fragmentos` para serem o elemento pai do `jsx`. Os fragmentos permitem agrupar uma lista de crianças sem adicionar nós
```suggestion
Explicação: Primeiro aceitamos as 3 props neste componente. Depois, utilizamos `fragmentos` para serem o elemento pai do `jsx`. Os fragmentos permitem agrupar uma lista de elementos-filhos sem adicionar nodos extras ao DOM.
```

2021-04-06 04:42 UTC, adrianoapj commented on docs/workshops/calculadora-react/README.md
> +Em seguida, utilizamos [operadores ternários](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Conditional_Operator) para tornar diferente o `div` dependendo da situação. S
```suggestion
Em seguida, utilizamos [operadores ternários](https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Reference/Operators/Conditional_Operator) para tornar diferente o `div` dependendo da situação. Se o `isInput` for verdadeiro, ele renderizará o `div` com o `nome de classe` `input`, caso contrário renderizará outro `div`.
```

2021-04-06 04:42 UTC, adrianoapj commented on docs/workshops/calculadora-react/README.md
> +    if (!isNaN(val) || val === 'L' || val === '.') {
Certo, aqui temos um problema. Note que aqui ocorre uma verificação se `val` é igual a L, contudo, no código o botão de limpar na verdade é C, o que faz com que o botão de limpar não passe nessa verificação aqui...
Resultado: o botão de limpar fica laranja, enquanto no workshop original ele é branco, assim como os números.

Possíveis soluções:

- Corrigir a verificação e todas as prints que mostram o botão de limpar como sendo laranja
- Manter o botão laranja, e remover essa verificação do código, bem como sua explicação logo abaixo.

2021-04-06 04:42 UTC, adrianoapj commented on docs/workshops/calculadora-react/README.md
> +Para o botão que tem `=` como children, passaremos a prop `onClick=={calcular}` para ele.
```suggestion
Para o botão que tem `=` como children, passaremos a prop `onClick={calcular}` para ele.
```

2021-04-06 04:42 UTC, adrianoapj commented on docs/workshops/gerador-de-citacoes-flask/README.md
> +Anteriormente, importamos o módulo `requests`, que utilizaremos para fazer [requisições HTTP](https://developer.mozilla.org/en-US/docs/Web/HTTP/Messages).
```suggestion
Anteriormente, importamos o módulo `requests`, que utilizaremos para fazer [requisições HTTP](https://developer.mozilla.org/pt-BR/docs/Web/HTTP/Messages).
```

2021-04-06 04:42 UTC, adrianoapj commented on docs/workshops/jogo-da-velha/README.md
> +Precisamos de um loop para executar o jogo, pois haverá até 9 rodadas (uma para cada espaço). Portanto, vamos fazer um loop de tempo, desde que uma variável seja verdadeira. Dê para ela um nome como
```suggestion
Precisamos de um loop para executar o jogo, pois haverá até 9 rodadas (uma para cada espaço). Portanto, vamos fazer um loop de tempo, desde que uma variável seja verdadeira. Dê para ela um nome como `acabou`. O laço funcionará desde que `acabou` seja `False` (falso). Podemos mais tarde mudar o `acabou` para `True` (verdadeiro) quando um jogador ganhar ou a partida for um empate. Em nosso loop, primeiro imprimimos o tabuleiro e pedimos uma entrada ao Jogador 1 ou simplesmente ao Jogador `X`. Depois imprimimos novamente o tabuleiro, mas desta vez com o sinal colocado no tabuleiro. Note que temos que reduzir o `PegarNumero()` em um para o índice de `tabuleiro[]`. Então, fazemos a mesma coisa para o Jogador `O`.
```

2021-04-06 04:42 UTC, adrianoapj commented on docs/workshops/jogo-da-velha/README.md
> +Agora você tem o controle total sobre este código. Vá em frente e mexa com ele para ver se você pode encontrar maneiras de torná-lo mais divertido. Aqui estão algumas idéias:
```suggestion
Agora você tem o controle total sobre este código. Vá em frente e mexa com ele para ver se você pode encontrar maneiras de torná-lo mais divertido. Aqui estão algumas ideias:
```

2021-04-06 04:42 UTC, adrianoapj commented on docs/workshops/mundos-vr/README.md
> +As luzes direcionais são como uma fonte de luz que está infinitamente distante, mas brilhando de uma direção específica, como o sol. Devemos especificar para onde a luz está apontando, fazemos isso u
```suggestion
As luzes direcionais são como uma fonte de luz que está infinitamente distante, mas brilhando de uma direção específica, como o sol. Devemos especificar para onde a luz está apontando, fazemos isso utilizando o atributo `target` (alvo), que aponta para a posição do objeto filho.
```

2021-04-06 04:42 UTC, adrianoapj commented on docs/workshops/roda-a-roda/README.md
> +Uma vez feito isso, adicione um `<div class="caixa2">` após seu div `caixa1`, depois copie e cole todos os 4 divs `span` que você já criou e personalize-os assim.👇
```suggestion
Uma vez feito isso, adicione um `<div class="caixa2">` após seu div `caixa1`, depois copie e cole todos os 4 `span` que você já criou e personalize-os assim.👇
```

2021-04-09 12:29 UTC, vitorvavolizza commented
@adrianoapj @farreltobias @gabriellimma tudo certo para dar merge?

2021-04-09 13:42 UTC, farreltobias commented on docs/workshops/calculadora-react/README.md
> +    if (!isNaN(val) || val === 'L' || val === '.') {
@vitorvavolizza isso foi corrigido?

2021-04-09 14:18 UTC, vitorvavolizza commented on docs/workshops/calculadora-react/README.md
> +    if (!isNaN(val) || val === 'L' || val === '.') {
acabei de corrigir. Optei por deixar o botãozinho "Clear" cinza como o original.

2021-04-09 14:49 UTC, adrianoapj approved these changes

2021-04-09 17:34 UTC, adrianoapj commented
Fala, @vitorvavolizza, tudo certo agora com as alterações feitas. Eu apenas fiz um rebase dos commits que você fez via GitHub e uni eles em um só.

2021-04-09 18:32 UTC, vitorvavolizza commented
fechamos esses workshops então, vou subir o código

2021-04-09 18:33 UTC, merged